# Generated by Django 4.0.1 on 2022-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='plataforma',
            field=models.CharField(default='a', max_length=80),
            preserve_default=False,
        ),
    ]
