# Generated by Django 4.0.1 on 2022-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBlogApp', '0002_evento_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('plataforma', models.CharField(max_length=80)),
            ],
        ),
    ]
